---

- block:
  - name: create virtual environment and install Python requirements (Ubuntu 15+)
    pip:
      executable: pip3
      virtualenv_command: pyvenv
      virtualenv: "{{ site_root }}/environ"
      requirements: "{{ site_root }}/requirements/pip.{{ deployment }}"
    when: ansible_lsb.major_release|int >= 15

  - name: install Python requirements (Ubuntu 14)
    pip:
      executable: pip3
      virtualenv: "{{ site_root }}/environ"
      virtualenv_python: python3
      requirements: "{{ site_root }}/requirements/pip.{{ deployment }}"
    when: ansible_lsb.major_release|int <= 14

  when: ansible_distribution == "Ubuntu"

- name: update virtual environment activation script
  lineinfile:
    state: present
    dest: "{{ site_root }}/environ/bin/activate"
    line: "{{ item  }}"
    insertafter: EOF
  with_items:
    - export DJANGO_SETTINGS_MODULE={{ site_name }}.settings.{{ deployment }}
    - export PYTHONPATH={{ site_root }}/{{ site_name }}:$PYTHONPATH
