---

- name: system configuration
  hosts: all
  roles:
    - { role: system }
    - { role: sshkey }

- name: web setup
  hosts: production
  roles:
    - { role: postfix }
    - { role: web }

- name: common configuration
  hosts: all
  roles:
    - { role: shell }
    - { role: clone }

- name: database configuration
  hosts: production
  roles:
    - { role: postgresql }

- name: common configuration
  hosts: all
  roles:
    - { role: virtualenv }
    - { role: django }
    - { role: nodejs }

- name: final installation
  hosts: production
  tasks:

    - name: set database URL (virtualenv)
      lineinfile:
        state: present
        dest: "{{ site_root }}/environ/bin/activate"
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - export DATABASE_URL=postgres://{{ project_name }}@localhost/{{ project_name }}

    - name: set database URL (uwsgi)
      lineinfile:
        state: present
        dest: /etc/uwsgi/{{ project_name }}.ini
        line: "{{ item }}"
        insertafter: EOF
      with_items:
        - export env = DATABASE_URL=postgres://{{ project_name }}@localhost/{{ project_name }}

    - name: migrate
      shell: . ../environ/bin/activate && ./manage.py migrate
      args:
        chdir: "{{ site_root }}/{{ project_name }}"
        executable: /bin/bash

    - name: build static files
      shell: . environ/bin/activate && gulp build
      args:
        chdir: "{{ site_root }}"
        executable: /bin/bash

    - name: collect static files
      shell: . environ/bin/activate && ./manage.py collectstatic --no-input
      args:
        chdir: "{{ site_root }}"
        executable: /bin/bash

    - name: change ownership of repository
      file: path={{ site_root }} recurse=yes owner={{ web_user }} group={{ web_group }} state=directory

- name: web configuration
  hosts: production
  roles:
    - { role: uwsgi }
    - { role: nginx }
