---

# - hosts: all
#   vars_prompt:
#     - name: heroku_password
#       prompt: Please enter your Heroku password
#       private: yes

- name: common configuration
  hosts: all
  roles:
    - { role: system }
    - { role: sshkey }
    - { role: shell }
    - { role: clone }
    - { role: virtualenv }
    - { role: django }
    - { role: nodejs }
