---

- name: system configuration
  hosts: all
  roles:
    - { role: system }
    - { role: sshkey }

- name: web setup
  hosts: production
  roles:
    - { role: web }

- name: common configuration
  hosts: all
  roles:
    - { role: shell }
    - { role: clone }

- name: database configuration
  hosts: production
  roles:
    - { role: postgresql }

- name: common configuration
  hosts: all
  roles:
    - { role: virtualenv }
    - { role: django }
    - { role: nodejs }

- name: final installation
  hosts: production
  tasks:

    - name: migrate
      shell: ./manage.py migrate
      args:
        chdir: "{{ site_root }}/{{ project_name }}"

    - name: build static files
      shell: grunt build
      args:
        chdir: "{{ site_root }"

    - name: collect static files
      shell: ./manage.py collectstatic
      args:
        chdir: "{{ site_root }"

    - name: change ownership of repository
      file: path={{ site_root }} recurse=yes owner={{ web_user }} group={{ web_group }} state=directory

- name: web configuration
  hosts: production
  roles:
    - { role: uwsgi }
    - { role: nginx }
