---

- block:
  - name: update system (Arch)
    pacman: update_cache=yes upgrade=full

  - name: install virtualenv (Arch)
    pacman: name=$item state=latest
    with_items:
      - python
      - python-virtualenv

  when: ansible_distribution == "Arch"

- block:
  - name: install aptitude (Ubuntu)
    become: yes
    apt: name=aptitude state=latest

  - name: update system (Ubuntu)
    become: yes
    apt: update_cache=yes upgrade=full
    when: ansible_lsb.major_release|int <= 14

  - name: install base packages (Ubuntu)
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - python3
      - python3-pip
      - git
      - libffi-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - xvfb

  - name: install base packages (Ubuntu 14)
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - python-virtualenv
    when: ansible_lsb.major_release|int <= 14

  - name: install packages (Ubuntu 15+)
    become: yes
    apt: name={{ item }} state=latest
    with_items:
      - python3-venv
    when: ansible_lsb.major_release|int >= 15

  when: ansible_distribution == "Ubuntu"
